### ISSUE TITLE
Authorization parameters

### ISSUE THREAD

**Issue by zacharynevin** [Ideame/paypal-adaptive-sdk-nodejs#8]
In the Paypal adaptive payments credentials, you are given the following credentials:
- Test account: example@example.com
- Client ID: *******_client_id**_****
- Secret: *****_signature**_*****

My question is, how does this map onto `userId`, `password` (I assume this is the paypal password), and `signature`? I have the following put down, but I keep getting authentication errors:

```
paypalSDK = new Paypal({
  userId: ********client_id*******,
  password: *****,
  signature: ******signature********,
  sandboxEmailAddress: 'example@example.com',
  sandbox: true
})
```

**Comment by misterch0c** [comment]
Isn't the app-id needed? I can see it's setup in the default configuration var.
However I also get authorization error after requesting and setting api credentials : (

**Comment by gaguirre** [comment]
@misterch0c the appId is needed when you want to go live, until that moment you can use the sandbox and the appId is already set for that case... just set `sandbox: true`.

Hope it helps you! Also, i suggest check the link posted above.
